//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session_1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int ID { get; set; }
        public Nullable<int> ID_access { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual AccessToStatus AccessToStatus { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
