//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session_1.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlazkiSaveEntities : DbContext
    {
        public GlazkiSaveEntities()
            : base("name=GlazkiSaveEntities")
        {
        }

        private static GlazkiSaveEntities _context; // приват контекст

        public static GlazkiSaveEntities GetContext() // метод возврата контекста 
        {
            if (_context == null)
            {
                _context = new GlazkiSaveEntities(); 
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
