//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session_1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastDay { get; set; }
        public Nullable<System.TimeSpan> LastTime { get; set; }
        public Nullable<int> LogType { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual LogTypes LogTypes { get; set; }
    }
}
